# Generated by Django 4.1.4 on 2023-02-08 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('position', models.CharField(default='Staff', max_length=100)),
                ('joiningDate', models.DateField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'CustomUser',
                'verbose_name_plural': 'CustomUsers',
            },
        ),
        migrations.CreateModel(
            name='UnapprovedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('joiningDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('staffDepartment', models.CharField(blank=True, max_length=100)),
                ('staffPayScale', models.IntegerField(default=0)),
                ('staffImage', models.ImageField(default='default.png', upload_to='staffimage/')),
                ('staffLastUpdateDate', models.DateField(auto_now_add=True)),
                ('staffBio', models.TextField(default='Bio')),
                ('staffGender', models.CharField(max_length=1)),
                ('staffMobileNumber', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('studentClass', models.CharField(blank=True, max_length=100)),
                ('studentSubject', models.CharField(blank=True, max_length=100)),
                ('studentImage', models.ImageField(default='default.png', upload_to='studentimage/')),
                ('studentLastUpdateDate', models.DateField(auto_now_add=True)),
                ('studentBio', models.TextField(default='Bio')),
                ('studentGender', models.CharField(max_length=1)),
                ('studentMobileNumber', models.CharField(default='', max_length=100)),
                ('studentMarks', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('teacherSubject', models.CharField(max_length=100)),
                ('teacherImage', models.ImageField(default='default.png', upload_to='teacherimage/')),
                ('teacherLastUpdateDate', models.DateField(auto_now=True)),
                ('teacherPayScale', models.IntegerField(default=0)),
                ('teacherBio', models.TextField(default='Bio')),
                ('teacherGender', models.CharField(max_length=1)),
                ('teacherMobileNumber', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
