# Generated by Django 4.1.4 on 2023-02-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unapproveduser',
            name='position',
            field=models.CharField(default='Staff', max_length=100),
        ),
    ]
