# Generated by Django 4.1.4 on 2023-02-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_unapproveduser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staffDepartment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffGender',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffLastUpdateDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentClass',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentGender',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentLastUpdateDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentSubject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherGender',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherSubject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
