# Generated by Django 4.1.4 on 2023-02-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_staff_staffdepartment_alter_staff_staffgender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacherMobileNumber',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherSubject',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
