# Generated by Django 4.1.4 on 2023-02-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_teacher_teachermobilenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staffDepartment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffGender',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffMobileNumber',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentClass',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentGender',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentMobileNumber',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentSubject',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
