# Generated by Django 4.1.4 on 2022-12-18 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherId', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('teacherName', models.CharField(default='Guest Teacher', max_length=1000)),
                ('teacherUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('teacherImage', models.ImageField(upload_to='teacherimage/')),
                ('teacherJoiningDate', models.DateField(auto_now_add=True)),
                ('teacherBio', models.TextField()),
                ('teacherGender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=1)),
                ('teacherMobileNumber', models.CharField(max_length=100)),
                ('teacherSubject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.subject')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('studentId', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('studentName', models.CharField(default='Guest Student', max_length=1000)),
                ('studentImage', models.ImageField(upload_to='studentimage/')),
                ('studentJoiningDate', models.DateField(auto_now_add=True)),
                ('studentBio', models.TextField(blank=True, null=True)),
                ('studentGender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=1)),
                ('studentMobileNumber', models.CharField(max_length=100)),
                ('studentMarks', models.IntegerField(blank=True, null=True)),
                ('studentRemarks', models.TextField(blank=True, null=True)),
                ('studentRating', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True)),
                ('studentClass', models.ForeignKey(default='undefined', on_delete=django.db.models.deletion.SET_DEFAULT, to='base.standard')),
                ('studentSubject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.subject')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
