# Generated by Django 4.1.4 on 2022-12-12 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('teacherName', models.CharField(default='Guest Teacher', max_length=1000)),
                ('teacherImage', models.ImageField(upload_to='teacherimage/')),
                ('teacherJoiningDate', models.DateField(auto_now_add=True)),
                ('teacherBio', models.TextField()),
                ('teacherGender', models.CharField(max_length=1)),
                ('teacherMobileNumber', models.CharField(max_length=100)),
                ('teacherSubject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.subject')),
                ('teacherUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
