# Generated by Django 4.1.4 on 2022-12-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacherGender',
            field=models.CharField(choices=[('M', 'm'), ('F', 'f'), ('O', 'o')], max_length=1),
        ),
    ]
