# Generated by Django 4.1.4 on 2022-12-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_initial'),
        ('user', '0002_teacher_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentSubject',
        ),
        migrations.AddField(
            model_name='student',
            name='studentSubject',
            field=models.ManyToManyField(blank=True, null=True, to='base.subject'),
        ),
    ]
