# Generated by Django 4.1.4 on 2022-12-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_initial'),
        ('user', '0003_remove_student_studentsubject_student_studentsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentSubject',
            field=models.ManyToManyField(blank=True, to='base.subject'),
        ),
    ]
