# Generated by Django 4.1.4 on 2022-12-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_student_studentsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Teacher', 'Teacher'), ('Student', 'Student')], default='Staff', max_length=100),
        ),
    ]
