# Generated by Django 4.1.4 on 2022-12-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Admin', 'Admin')], default='Staff', max_length=100),
        ),
    ]
