# Generated by Django 4.1.4 on 2022-12-18 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_department_remove_standard_students_and_more'),
        ('user', '0006_alter_customuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacherPayScale',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('staffId', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('staffName', models.CharField(default='Guest Staff', max_length=1000)),
                ('staffPayScale', models.IntegerField(default=0)),
                ('staffImage', models.ImageField(upload_to='staffimage/')),
                ('staffJoiningDate', models.DateField(auto_now_add=True)),
                ('staffBio', models.TextField()),
                ('staffGender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=1)),
                ('staffMobileNumber', models.CharField(max_length=100)),
                ('staffDepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.department')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
            },
        ),
    ]
