# Generated by Django 4.1.4 on 2022-12-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_teacher_teacherpayscale_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staffBio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherBio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
