# Generated by Django 4.1.4 on 2022-12-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_staff_staffbio_alter_staff_staffimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
