# Generated by Django 4.1.4 on 2022-12-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_waitingapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staffId',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentId',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacherId',
        ),
    ]
