# Generated by Django 4.1.4 on 2022-12-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingapproval',
            name='name',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
