# Generated by Django 4.1.4 on 2022-12-12 05:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectId', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('subjectName', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
