# Generated by Django 4.1.4 on 2022-12-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_position'),
        ('base', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentName', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='standard',
            name='students',
        ),
        migrations.AddField(
            model_name='standard',
            name='classStudents',
            field=models.ManyToManyField(blank=True, related_name='Admitted_Class_Student', to='user.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subjectStudent',
            field=models.ManyToManyField(blank=True, related_name='Admitted_Subject_Student', to='user.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subjectTeacher',
            field=models.ManyToManyField(blank=True, related_name='Appointed_Teacher', to='user.teacher'),
        ),
    ]
