# Generated by Django 4.1.4 on 2022-12-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_department_remove_standard_students_and_more'),
        ('user', '0007_teacher_teacherpayscale_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='departmentEmployee',
            field=models.ManyToManyField(blank=True, related_name='Appointed_Staff', to='user.staff'),
        ),
    ]
