# Generated by Django 4.1.4 on 2022-12-18 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_department_departmentemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentEmployee',
            field=models.ManyToManyField(blank=True, related_name='Appointed_Staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='standard',
            name='classStudents',
            field=models.ManyToManyField(blank=True, related_name='Admitted_Class_Student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectStudent',
            field=models.ManyToManyField(blank=True, related_name='Admitted_Subject_Student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectTeacher',
            field=models.ManyToManyField(blank=True, related_name='Appointed_Teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
