# Generated by Django 4.1.4 on 2022-12-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_department_departmentemployee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='departmentEmployee',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='classStudents',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subjectStudent',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subjectTeacher',
        ),
    ]
